# Generated by Django 5.2 on 2025-07-01 11:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryManagement', '0002_inventorycategory_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='inventorycategory',
            unique_together={('name', 'created_by')},
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('name', 'created_by')},
        ),
    ]
