# Generated by Django 5.2 on 2025-07-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryManagement', '0003_alter_inventorycategory_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='code',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
