import type { MenuItem, Discount, Table, Order } from "./types"

export const menuItems: MenuItem[] = [
  {
    id: 1,
    name: "Classic Burger",
    description: "Juicy beef patty with lettuce, tomato, and special sauce",
    price: 12.99,
    image: "/placeholder.svg?height=200&width=200",
    category: 1,
    available: true,
    featured: true,
    allergens: ["gluten", "dairy"],
    nutritionalInfo: {
      calories: 650,
      protein: 35,
      carbs: 40,
      fat: 25,
    },
    quantity: 0,
  },
  {
    id: 2,
    name: "Caesar Salad",
    description: "Crisp romaine lettuce with Caesar dressing and croutons",
    price: 8.99,
    image: "/placeholder.svg?height=200&width=200",
    category: 2,
    available: true,
    allergens: ["gluten", "dairy", "eggs"],
    nutritionalInfo: {
      calories: 320,
      protein: 10,
      carbs: 15,
      fat: 12,
    },
    quantity: 0,
  },
  {
    id: 3,
    name: "Chocolate Cake",
    description: "Rich chocolate cake with ganache frosting",
    price: 6.99,
    image: "/placeholder.svg?height=200&width=200",
    category: 3,
    available: true,
    allergens: ["gluten", "dairy", "eggs"],
    nutritionalInfo: {
      calories: 450,
      protein: 5,
      carbs: 60,
      fat: 20,
    },
    quantity: 0,
  },
  {
    id: 4,
    name: "Iced Coffee",
    description: "Cold brewed coffee served over ice",
    price: 3.99,
    image: "/placeholder.svg?height=200&width=200",
    category: 4,
    available: true,
    nutritionalInfo: {
      calories: 120,
      protein: 0,
      carbs: 15,
      fat: 5,
    },
    quantity: 0,
  },
  {
    id: 5,
    name: "Margherita Pizza",
    description: "Classic pizza with tomato sauce, mozzarella, and basil",
    price: 14.99,
    image: "/placeholder.svg?height=200&width=200",
    category: 1,
    available: true,
    allergens: ["gluten", "dairy"],
    nutritionalInfo: {
      calories: 850,
      protein: 35,
      carbs: 90,
      fat: 40,
    },
    quantity: 0,
  },
  {
    id: 6,
    name: "Garlic Bread",
    description: "Toasted bread with garlic butter and herbs",
    price: 4.99,
    image: "/placeholder.svg?height=200&width=200",
    category: 2,
    available: false,
    allergens: ["gluten", "dairy"],
    nutritionalInfo: {
      calories: 320,
      protein: 6,
      carbs: 40,
      fat: 18,
    },
    quantity: 0,
  },
]

export const discounts: Discount[] = [
  {
    id: 1,
    name: "Summer Special",
    description: "20% off all main courses",
    start_date: "2023-06-01",
    end_date: "2023-08-31",
    active: true,
    applicable_items: menuItems.filter((item) => item.category === 1).map((item) => item.id),
    discount_percentage: 20,
  },
  {
    id: 2,
    name: "Happy Hour",
    description: "Buy one get one free on all beverages",
    start_date: "2023-01-01",
    end_date: "2023-12-31",
    active: true,
    applicable_items: menuItems.filter((item) => item.category === 4).map((item) => item.id),
    discount_percentage: 100, // or a value that makes sense for BOGO
  },
  {
    id: 3,
    name: "Lunch Special",
    description: "$5 off orders over $30",
    start_date: "2023-01-01",
    end_date: "2023-12-31",
    active: true,
    applicable_items: [],
    discount_percentage: 5,
  },
]

export const tables: Table[] = [
  {
    id: '1',
    number: 1,
    capacity: 2,
    status: "available",
    location: "Window",
  },
  {
    id: '2',
    number: 2,
    capacity: 4,
    status: "occupied",
    location: "Center",
  },
  {
    id: '3',
    number: 3,
    capacity: 6,
    status: "reserved",
    location: "Patio",
    reservationDetails: {
      name: "John Smith",
      time: "2023-07-15T19:00:00",
      phone: "555-123-4567",
    },
  },
  {
    id: "4",
    number: 4,
    capacity: 2,
    status: "available",
    location: "Bar",
  },
  {
    id: '5',
    number: 5,
    capacity: 8,
    status: "reserved",
    location: "Private Room",
    reservationDetails: {
      name: "Corporate Event",
      time: "2023-07-16T18:30:00",
      phone: "555-987-6543",
    },
  },
]

export const orders: Order[] = [
  {
    id: "1",
    tableId: "2",
    tableNumber: 2,
    items: [
      {
        menuItemId: "1",
        name: "Classic Burger",
        price: 12.99,
        quantity: 2,
      },
      {
        menuItemId: "4",
        name: "Iced Coffee",
        price: 3.99,
        quantity: 2,
      },
    ],
    status: "preparing",
    total: 33.96,
    createdAt: "2023-07-15T12:30:00",
    updatedAt: "2023-07-15T12:35:00",
    paymentStatus: "pending",
  },
  {
    id: "2",
    tableId: "3",
    tableNumber: 3,
    items: [
      {
        menuItemId: "5",
        name: "Margherita Pizza",
        price: 14.99,
        quantity: 1,
      },
      {
        menuItemId: "2",
        name: "Caesar Salad",
        price: 8.99,
        quantity: 1,
      },
      {
        menuItemId: "3",
        name: "Chocolate Cake",
        price: 6.99,
        quantity: 1,
      },
    ],
    status: "ready",
    total: 30.97,
    createdAt: "2023-07-15T12:15:00",
    updatedAt: "2023-07-15T12:40:00",
    specialInstructions: "No onions on the pizza please",
    paymentStatus: "paid",
    paymentMethod: "card",
  },
  {
    id: "3",
    tableId: "5",
    tableNumber: 5,
    items: [
      {
        menuItemId: "1",
        name: "Classic Burger",
        price: 12.99,
        quantity: 4,
      },
      {
        menuItemId: "2",
        name: "Caesar Salad",
        price: 8.99,
        quantity: 2,
      },
      {
        menuItemId: "4",
        name: "Iced Coffee",
        price: 3.99,
        quantity: 6,
      },
    ],
    status: "pending",
    total: 95.9,
    createdAt: "2023-07-15T12:45:00",
    updatedAt: "2023-07-15T12:45:00",
    customerName: "Corporate Event",
    paymentStatus: "pending",
  },
]
