# Generated by Django 5.2 on 2025-07-06 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EsewaCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esewa_product_code', models.CharField(blank=True, help_text='eSewa product code (alphanumeric only)', max_length=100, null=True)),
                ('esewa_secret_key_encrypted', models.TextField(blank=True, help_text='Encrypted eSewa secret key', null=True)),
                ('esewa_display_name', models.CharField(blank=True, help_text='Display name for the eSewa account (optional)', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether these credentials are active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_accessed', models.DateTimeField(blank=True, help_text='Last time credentials were accessed', null=True)),
                ('admin', models.OneToOneField(help_text='The admin user who owns these credentials', on_delete=django.db.models.deletion.CASCADE, related_name='esewa_credentials', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created these credentials', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_esewa_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'eSewa Credential',
                'verbose_name_plural': 'eSewa Credentials',
                'db_table': 'esewa_credentials',
            },
        ),
        migrations.CreateModel(
            name='EsewaCredentialAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('viewed', 'Viewed'), ('deleted', 'Deleted'), ('enabled', 'Enabled'), ('disabled', 'Disabled')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esewa_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='esewaSecretKey.esewacredentials')),
            ],
            options={
                'verbose_name': 'eSewa Credential Audit Log',
                'verbose_name_plural': 'eSewa Credential Audit Logs',
                'db_table': 'esewa_credential_audit_logs',
            },
        ),
        migrations.AddIndex(
            model_name='esewacredentials',
            index=models.Index(fields=['admin', 'is_active'], name='esewa_crede_admin_i_95d94a_idx'),
        ),
        migrations.AddIndex(
            model_name='esewacredentials',
            index=models.Index(fields=['created_at'], name='esewa_crede_created_9a4fa6_idx'),
        ),
        migrations.AddIndex(
            model_name='esewacredentialauditlog',
            index=models.Index(fields=['credential', 'action'], name='esewa_crede_credent_04aa3e_idx'),
        ),
        migrations.AddIndex(
            model_name='esewacredentialauditlog',
            index=models.Index(fields=['user', 'timestamp'], name='esewa_crede_user_id_3cb238_idx'),
        ),
        migrations.AddIndex(
            model_name='esewacredentialauditlog',
            index=models.Index(fields=['timestamp'], name='esewa_crede_timesta_1e56bf_idx'),
        ),
    ]
