# Generated by Django 5.2 on 2025-07-06 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esewaSecretKey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='esewacredentials',
            name='environment',
            field=models.CharField(choices=[('test', 'Test Environment'), ('production', 'Production Environment')], default='test', help_text='eSewa environment (test or production)', max_length=20),
        ),
    ]
