# Generated by Django 5.2 on 2025-07-06 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esewaSecretKey', '0002_esewacredentials_environment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EsewaOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'eSewa OTP',
                'verbose_name_plural': 'eSewa OTPs',
                'db_table': 'esewa_otps',
            },
        ),
        migrations.RemoveIndex(
            model_name='esewacredentialauditlog',
            name='esewa_crede_credent_04aa3e_idx',
        ),
        migrations.RemoveIndex(
            model_name='esewacredentialauditlog',
            name='esewa_crede_timesta_1e56bf_idx',
        ),
        migrations.AddIndex(
            model_name='esewacredentialauditlog',
            index=models.Index(fields=['credential', 'timestamp'], name='esewa_crede_credent_fd1877_idx'),
        ),
        migrations.AddField(
            model_name='esewaotp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esewa_otps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='esewaotp',
            index=models.Index(fields=['user', 'created_at'], name='esewa_otps_user_id_b02e39_idx'),
        ),
        migrations.AddIndex(
            model_name='esewaotp',
            index=models.Index(fields=['is_used'], name='esewa_otps_is_used_2bafe1_idx'),
        ),
    ]
