# Generated by Django 5.2 on 2025-07-06 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esewaSecretKey', '0003_esewaotp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EsewaVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esewa_verification_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'eSewa Verification Token',
                'verbose_name_plural': 'eSewa Verification Tokens',
                'db_table': 'esewa_verification_tokens',
                'indexes': [models.Index(fields=['token'], name='esewa_verif_token_40a59f_idx'), models.Index(fields=['user', 'created_at'], name='esewa_verif_user_id_5be7c0_idx'), models.Index(fields=['is_used'], name='esewa_verif_is_used_0e4756_idx')],
            },
        ),
    ]
