# Generated by Django 5.2 on 2025-05-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentaction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='otp',
            new_name='code',
        ),
        migrations.AddField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('signup', 'Signup'), ('forgot', 'Forgot Password'), ('reset', 'Reset Password')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
