# Generated by Django 5.2 on 2025-05-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentaction', '0002_rename_otp_otp_code_otp_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userevent',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
