# Generated by Django 5.2 on 2025-05-23 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentaction', '0003_userevent_ip_address_userevent_user_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='name',
            field=models.CharField(choices=[('view_menu', 'View Menu'), ('edit_menu', 'Edit Menu'), ('view_orders', 'View Orders'), ('manage_orders', 'Manage Orders'), ('view_tables', 'View Tables'), ('manage_tables', 'Manage Tables'), ('generate_qr', 'Generate QR Codes'), ('view_payments', 'View Payments'), ('view_customers', 'View Customers'), ('view_settings', 'View Settings'), ('edit_settings', 'Edit Settings'), ('view_users', 'View Users'), ('manage_users', 'Manage Users')], max_length=100, unique=True),
        ),
    ]
