# Generated by Django 5.2 on 2025-05-23 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentaction', '0004_customuser_created_by_alter_userpermission_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
