# Generated by Django 5.2 on 2025-05-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentaction', '0005_remove_customuser_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userevent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='user',
        ),
        migrations.AddField(
            model_name='otp',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='UserEvent',
        ),
    ]
