# Generated by Django 5.2 on 2025-05-23 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentaction', '0007_remove_otp_email_customuser_otp_user_userevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentaction.customuser'),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentaction.customuser'),
        ),
    ]
