# Generated by Django 5.2 on 2025-05-23 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentaction', '0008_alter_otp_user_alter_userevent_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userevent',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rolepermission',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='rolepermission',
            name='role',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='UserPermission',
        ),
        migrations.DeleteModel(
            name='RolePermission',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
