# Generated by Django 5.2 on 2025-06-13 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaynmentANDreview', '0002_alter_review_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
