# Generated by Django 5.2 on 2025-06-13 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaynmentANDreview', '0005_alter_review_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='customer',
        ),
    ]
