# Generated by Django 5.2 on 2025-06-14 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaynmentANDreview', '0006_remove_review_customer'),
        ('qrgenerator', '0006_order_extra_charges_applied'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaiterCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiter_calls', to='qrgenerator.table')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
