# Generated by Django 5.2 on 2025-06-15 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaynmentANDreview', '0007_waitercall'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WaiterCall',
        ),
    ]
