# Generated by Django 5.2 on 2025-05-24 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserRole', '0003_customuser_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='created_by',
        ),
    ]
