# Generated by Django 5.2 on 2025-05-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRole', '0004_remove_customuser_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
