# Generated by Django 5.2 on 2025-05-24 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserRole', '0006_alter_customuser_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
