# Generated by Django 5.2 on 2025-05-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRole', '0009_role_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='permissions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
