# Generated by Django 5.2 on 2025-05-26 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserRole', '0002_add_permissions_field'),
        ('UserRole', '0013_customuser_created_by_customuser_is_employee'),
    ]

    operations = [
    ]
