# Generated by Django 5.2 on 2025-06-01 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserRole', '0015_alter_customuser_options_customuser_admin_group'),
    ]

    operations = [
    ]
