# Generated by Django 5.2 on 2025-06-01 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserRole', '0016_merge_20250601_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='admin_group',
        ),
    ]
