# Generated by Django 5.2 on 2025-06-02 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserRole', '0017_remove_customuser_admin_group'),
    ]

    operations = [
    ]
