# Generated by Django 5.2 on 2025-06-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRole', '0018_add_qr_code_and_account_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('menu_manager', 'Menu Manager'), ('order_manager', 'Order Manager'), ('customer_support', 'Customer Support'), ('qr_code_manager', 'QR-Code Manager'), ('account_manager', 'Account Manager')], default='menu_manager', max_length=20),
        ),
    ]
