# Generated by Django 5.2 on 2025-06-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRole', '0020_alter_customuser_is_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_employee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
