# Generated by Django 5.2 on 2025-06-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRole', '0021_alter_customuser_is_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_employee',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
