# Generated by Django 5.2 on 2025-06-06 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrgenerator', '0003_table_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='admin',
        ),
    ]
