# Generated by Django 5.2 on 2025-06-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgenerator', '0005_table_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='extra_charges_applied',
            field=models.JSONField(blank=True, default=list, help_text='Stores applied extra charges (label, amount) at checkout.'),
        ),
    ]
