# Generated by Django 5.2 on 2025-06-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgenerator', '0006_order_extra_charges_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitercall',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved')], default='active', max_length=20),
        ),
    ]
