# Generated by Django 5.2 on 2025-06-29 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgenerator', '0008_alter_waitercall_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_uuid',
            field=models.CharField(blank=True, help_text='eSewa transaction UUID for linking payments', max_length=100, null=True),
        ),
    ]
