# Generated by Django 5.2 on 2025-06-29 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgenerator', '0010_alter_order_transaction_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_uuid',
            field=models.CharField(blank=True, help_text='eSewa transaction UUID for linking payments', max_length=500, null=True, unique=True),
        ),
    ]
