# Generated by Django 5.2 on 2025-06-15 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EsewaIntegration', '0003_rename_product_id_esewatransaction_transaction_uuid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='esewatransaction',
            old_name='transaction_uuid',
            new_name='product_id',
        ),
        migrations.RemoveField(
            model_name='esewatransaction',
            name='order',
        ),
        migrations.RemoveField(
            model_name='esewatransaction',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='esewatransaction',
            name='reference_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='esewatransaction',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='esewatransaction',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
