# Generated by Django 5.2 on 2025-06-15 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EsewaIntegration', '0005_alter_esewatransaction_user'),
        ('qrgenerator', '0008_alter_waitercall_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='esewatransaction',
            old_name='product_id',
            new_name='transaction_uuid',
        ),
        migrations.RemoveField(
            model_name='esewatransaction',
            name='reference_id',
        ),
        migrations.RemoveField(
            model_name='esewatransaction',
            name='user',
        ),
        migrations.AddField(
            model_name='esewatransaction',
            name='order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='esewa_transactions', to='qrgenerator.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='esewatransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='esewatransaction',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='INITIATED', max_length=20),
        ),
    ]
