# Generated by Django 5.2 on 2025-06-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EsewaIntegration', '0006_rename_product_id_esewatransaction_transaction_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esewatransaction',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='INITIATED', max_length=20),
        ),
    ]
