# Generated by Django 5.2 on 2025-06-28 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EsewaIntegration', '0007_alter_esewatransaction_status'),
        ('qrgenerator', '0008_alter_waitercall_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esewatransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='esewa_transactions', to='qrgenerator.order'),
        ),
    ]
