# Generated by Django 5.2 on 2025-06-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EsewaIntegration', '0008_alter_esewatransaction_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='esewatransaction',
            name='order_details',
            field=models.TextField(blank=True, help_text='JSON string of order details for recreation', null=True),
        ),
    ]
