# Generated by Django 5.2 on 2025-07-09 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended'), ('pending_payment', 'Pending Payment')], default='trial', max_length=20),
        ),
    ]
