# Generated by Django 5.2 on 2025-07-09 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0002_alter_subscription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='trial_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
