# Generated by Django 5.2 on 2025-07-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0003_alter_subscription_trial_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='payer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='payment_method',
            field=models.CharField(default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='manual_payment_screenshots/'),
        ),
        migrations.AlterField(
            model_name='billinghistory',
            name='payment_method',
            field=models.CharField(choices=[('esewa', 'eSewa'), ('cash', 'Cash'), ('other', 'Other'), ('manual', 'Manual')], default='esewa', max_length=20),
        ),
    ]
